import {createViewer} from './viewer.js?v=1';
import {createGestureController,clamp} from './controls.js?v=1';
import {createHandControl} from '../camera.js?v=5';
const $=id=>document.getElementById(id),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let viewer,webcam=false,busy=false,generation=0,engineering=false;const visited=new Set(),gestures=createGestureController();
const hand=createHandControl($('video'),$('overlay'),$('tracking-label'),{maxHands:2});
const components={arrays:{number:'01',title:'Solar arrays',copy:'These wings collect sunlight and turn it into electricity. The station uses that energy to run equipment and support its crew.',question:'Turn on engineering view. Where does the energy go?'},thrusters:{number:'02',title:'Electric thrusters',copy:'The Power and Propulsion Element uses electricity to power its thrusters. They help the spacecraft change and maintain its orbit.',question:'Look behind the power module. Can you find the four illustrative thrusters?'},habitat:{number:'03',title:'Habitat',copy:'Astronauts need a place to live, work, and carry out research. This illustrative living module is connected to the station’s power system.',question:'Follow the energy path from the arrays to the living space.'}};
function showComponent(name){const item=components[name];if(!item)return;visited.add(name);viewer.focus(name);gestures.reset();$('component-number').textContent=item.number+' // COMPONENT';$('component-title').textContent=item.title;$('component-copy').textContent=item.copy;$('component-question').textContent=item.question;$('component-info').hidden=false;document.querySelectorAll('[data-component]').forEach(b=>{b.classList.toggle('visited',visited.has(b.dataset.component));b.classList.toggle('selected',b.dataset.component===name);b.setAttribute('aria-pressed',b.dataset.component===name);b.querySelector('i').textContent=visited.has(b.dataset.component)?'FOUND':'EXPLORE';});$('found-count').textContent=visited.size+' / 3 COMPONENTS EXPLORED';$('discovery').hidden=visited.size!==3;}
function stopCamera(){document.querySelector('.control-guide').hidden=true;generation++;busy=false;webcam=false;hand.stop();gestures.reset();$('camera-preview').hidden=true;document.body.classList.remove('camera-on');$('camera-start').classList.remove('active');$('camera-start').disabled=false;$('camera-start').textContent='USE HAND CONTROL';$('camera-status').textContent='Drag to rotate. Scroll or pinch to zoom.';}
$('camera-start').addEventListener('click',async()=>{if(webcam){stopCamera();return;}if(busy)return;busy=true;const token=++generation;$('camera-start').disabled=true;$('camera-start').textContent='CONNECTING…';$('camera-status').textContent='Allow camera access. First setup loads the hand-tracking model.';try{await hand.enable();if(token!==generation)return;webcam=true;document.querySelector('.control-guide').hidden=false;$('camera-preview').hidden=false;document.body.classList.add('camera-on');$('camera-start').classList.add('active');$('camera-start').textContent='HAND CONTROL ON';$('camera-status').textContent='Pinch one hand to rotate. Pinch both to zoom.';}catch(error){if(token!==generation)return;$('camera-status').textContent=error.name==='NotAllowedError'?'Camera permission declined. Drag / scroll still work.':error.name==='NotFoundError'?'No camera found. Drag / scroll still work.':error.message;$('camera-start').textContent='USE HAND CONTROL';}finally{if(token===generation){busy=false;$('camera-start').disabled=false;}}});
$('pointer-start').addEventListener('click',()=>{stopCamera();host.focus({preventScroll:true});});$('disconnect').addEventListener('click',stopCamera);window.addEventListener('pagehide',()=>hand.stop());document.addEventListener('visibilitychange',()=>gestures.reset());
let pointers=new Map(),pointerAnchor=null,tap=null;const host=$('scene');
function readPointers(){const points=[...pointers.values()];if(points.length===1)return {kind:'rotate',x:points[0].x,y:points[0].y};if(points.length>=2)return {kind:'zoom',distance:Math.hypot(points[0].x-points[1].x,points[0].y-points[1].y)};return null;}
host.addEventListener('pointerdown',e=>{if(!viewer)return;host.focus({preventScroll:true});host.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});tap=pointers.size===1?{id:e.pointerId,x:e.clientX,y:e.clientY}:null;pointerAnchor=readPointers();gestures.reset();});
host.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!viewer)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const now=readPointers();if(pointerAnchor?.kind===now.kind){if(now.kind==='rotate')viewer.rotate((now.x-pointerAnchor.x)*.008,(now.y-pointerAnchor.y)*.008);else if(now.distance>5&&pointerAnchor.distance>5)viewer.zoom(clamp(pointerAnchor.distance/now.distance,.8,1.2));}pointerAnchor=now;});
host.addEventListener('pointerup',e=>{if(tap?.id===e.pointerId&&Math.hypot(e.clientX-tap.x,e.clientY-tap.y)<7){const r=host.getBoundingClientRect();const name=viewer?.pick((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2);if(name)showComponent(name);}tap=null;});
for(const type of ['pointerup','pointercancel','lostpointercapture'])host.addEventListener(type,e=>{pointers.delete(e.pointerId);pointerAnchor=readPointers();gestures.reset();});
host.addEventListener('wheel',e=>{if(!viewer)return;e.preventDefault();gestures.reset();viewer.zoom(Math.exp(clamp(e.deltaY,-150,150)*.002));},{passive:false});
host.addEventListener('keydown',e=>{if(!viewer)return;const actions={ArrowLeft:()=>viewer.rotate(-.12,0),ArrowRight:()=>viewer.rotate(.12,0),ArrowUp:()=>viewer.rotate(0,-.1),ArrowDown:()=>viewer.rotate(0,.1),'+':()=>viewer.zoom(.85),'=':()=>viewer.zoom(.85),'-':()=>viewer.zoom(1.18),'0':resetView};if(actions[e.key]){e.preventDefault();gestures.reset();actions[e.key]();}});
function resetView(){viewer?.reset();gestures.reset();$('component-info').hidden=true;document.querySelectorAll('[data-component]').forEach(b=>{b.classList.remove('selected');b.setAttribute('aria-pressed','false');});}
$('reset-view').addEventListener('click',resetView);$('zoom-in').addEventListener('click',()=>{gestures.reset();viewer?.zoom(.85);});$('zoom-out').addEventListener('click',()=>{gestures.reset();viewer?.zoom(1.18);});
$('close-info').addEventListener('click',()=>{$('component-info').hidden=true;});
document.querySelectorAll('[data-component]').forEach(b=>b.addEventListener('click',()=>{if(viewer)showComponent(b.dataset.component);}));
$('engineering-view').addEventListener('click',()=>{engineering=!engineering;$('engineering-view').setAttribute('aria-pressed',engineering);$('engineering-view').querySelector('span').textContent=engineering?'ON':'OFF';viewer?.setEngineering(engineering);});
let last=0,dx=0,dy=0,logZoom=0;
function frame(now){const dt=last?Math.min(.05,(now-last)/1000):0;last=now;if(document.hidden){requestAnimationFrame(frame);return;}let action={kind:'idle'};if(webcam){const result=hand.predict(now);if(!hand.ready){stopCamera();$('camera-status').textContent='Tracking interrupted. Mouse / touch remain available.';}else if(!pointers.size){action=gestures.step(result.hands||[]);$('camera-status').textContent=action.kind==='rotate'?'ROTATING // RELEASE PINCH TO HOLD':action.kind==='zoom'?'ZOOMING // SPREAD TO LOOK CLOSER':'PINCH TO GRAB // VIEW HELD';}else gestures.reset();}
 const smooth=1-Math.exp(-dt*18);if(action.kind==='rotate'){dx+=(action.dx*5-dx)*smooth;dy+=(action.dy*4-dy)*smooth;viewer.rotate(dx,dy);logZoom=0;}else if(action.kind==='zoom'){logZoom+=(Math.log(action.ratio)-logZoom)*smooth;viewer.zoom(Math.exp(logZoom));dx=dy=0;}else dx=dy=logZoom=0;
 $('distance').textContent='VIEW '+viewer.zoomPercent+'%';viewer.render(now/1000,reduced);requestAnimationFrame(frame);}
try{viewer=createViewer(host);$('loading').hidden=true;if(viewer.fallback)$('render-note').textContent='SOFTWARE VIEW // WEBGL UNAVAILABLE';requestAnimationFrame(frame);}catch(error){console.error(error);$('loading').textContent='Unable to initialize the viewer. Reload or try another browser.';}
