import * as THREE from '../vendor/three.module.js';
import {clamp} from './controls.js';
export function createViewer(host){
 const scene=new THREE.Scene();scene.background=new THREE.Color('#071321');const camera=new THREE.PerspectiveCamera(42,1,.1,200);let renderer,flat=null;
 try{renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;host.append(renderer.domElement);}catch{flat=document.createElement('canvas');host.append(flat);}
 (renderer?.domElement||flat).setAttribute('aria-hidden','true');scene.add(new THREE.HemisphereLight('#c7e0ff','#203144',2));const light=new THREE.DirectionalLight('#fff0bc',3);light.position.set(9,14,12);scene.add(light);const rim=new THREE.DirectionalLight('#7bbaff',2);rim.position.set(-10,0,-6);scene.add(rim);
 const model=new THREE.Group();scene.add(model);const silver=new THREE.MeshStandardMaterial({color:'#ccd6dc',metalness:.4,roughness:.5}),dark=new THREE.MeshStandardMaterial({color:'#263a4c'}),gold=new THREE.MeshStandardMaterial({color:'#d4ad54',metalness:.5,roughness:.5}),blue=new THREE.MeshStandardMaterial({color:'#205cab',metalness:.5,roughness:.45}),glass=new THREE.MeshStandardMaterial({color:'#83d8d2',emissive:'#205756',emissiveIntensity:.5});
 const groups={};for(const name of ['arrays','thrusters','habitat']){groups[name]=new THREE.Group();groups[name].userData.component=name;model.add(groups[name]);}
 function mesh(geometry,material,x,y,z,parent=model){const m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);parent.add(m);return m;}
 function box(w,h,d,material,x,y,z,parent){return mesh(new THREE.BoxGeometry(w,h,d),material,x,y,z,parent);}
 function cylinder(radius,length,material,x,y,z,parent){const m=mesh(new THREE.CylinderGeometry(radius,radius,length,16),material,x,y,z,parent);m.rotation.z=Math.PI/2;return m;}
 // Conceptual assembly for learning, not a reproduction of Gateway CAD.
 box(3.3,2.4,2.4,gold,-3.1,0,0);box(3.5,.1,2.6,dark,-3.1,1.25,0);box(.6,.6,2.4,silver,-.95,0,0);
 cylinder(1.15,4.4,silver,1.5,0,0,groups.habitat);cylinder(.9,1.8,silver,4.65,0,0,groups.habitat);cylinder(.65,.8,dark,5.85,0,0,groups.habitat);
 for(const x of [.0,.85,1.7,2.55,3.4]){const ring=mesh(new THREE.TorusGeometry(1.17,.055,4,16),dark,x,0,0,groups.habitat);ring.rotation.y=Math.PI/2;}
 box(.8,.55,.06,glass,2.2,.1,1.15,groups.habitat);box(.7,.08,3.6,silver,2.3,1.3,0,groups.habitat);
 for(const side of [-1,1]){box(.22,.22,2.8,silver,-3.1,0,side*2.3,groups.arrays);box(4.8,.08,6.7,silver,-3.1,0,side*6.7,groups.arrays);for(let x=0;x<4;x++)for(let z=0;z<7;z++)box(1.06,.025,.85,blue,-4.84+x*1.16,.06,side*6.7-2.9+z*.96,groups.arrays);box(.2,.2,2.8,silver,-3.1,0,side*10.9,groups.arrays);}
 for(const y of [-.65,.65])for(const z of [-.7,.7]){const m=mesh(new THREE.CylinderGeometry(.25,.4,.7,12),dark,-5.15,y,z,groups.thrusters);m.rotation.z=Math.PI/2;const glow=mesh(new THREE.ConeGeometry(.23,1.6,12),new THREE.MeshBasicMaterial({color:'#7cb7ff',transparent:true,opacity:.22}),-6.25,y,z,groups.thrusters);glow.rotation.z=-Math.PI/2;glow.userData.jet=true;glow.visible=false;}
 const moon=mesh(new THREE.SphereGeometry(6,20,12),new THREE.MeshStandardMaterial({color:'#78818d',roughness:1}),-15,-9,-30,scene);for(let i=0;i<14;i++){const a=i*2.4,b=.6+i%4*.4;const crater=mesh(new THREE.TorusGeometry(.25+i%3*.15,.05,4,10),dark,Math.sin(b)*Math.cos(a)*5.98,Math.cos(b)*5.98,Math.sin(b)*Math.sin(a)*5.98,moon);crater.lookAt(0,0,0);}
 const starPoints=[];for(let i=0;i<220;i++)starPoints.push(Math.sin(i*29)*75,Math.cos(i*17)*55,-45-(i%25));const stars=new THREE.BufferGeometry();stars.setAttribute('position',new THREE.Float32BufferAttribute(starPoints,3));scene.add(new THREE.Points(stars,new THREE.PointsMaterial({color:'#8caac6',size:.12})));
 const engineering=new THREE.Group();scene.add(engineering);const paths=[];for(const end of [new THREE.Vector3(-3.1,.3,-8),new THREE.Vector3(-3.1,.3,8),new THREE.Vector3(2.2,.3,0),new THREE.Vector3(-5.2,.3,0)]){const points=[end,new THREE.Vector3(-3.1,.3,0)];paths.push(points);engineering.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:'#80efc9',depthTest:false})));}engineering.visible=false;
 const dots=[];for(let i=0;i<12;i++){const d=mesh(new THREE.SphereGeometry(.08,6,4),new THREE.MeshBasicMaterial({color:'#80efc9',depthTest:false}),0,0,0,engineering);dots.push(d);}
 let azimuth=.62,elevation=.35,radius=34,target=new THREE.Vector3(),selected=null,lastSignature='',width=0,height=0;
 const focusPoints={arrays:{target:new THREE.Vector3(-3.1,0,4),radius:22},thrusters:{target:new THREE.Vector3(-5.1,0,0),radius:10},habitat:{target:new THREE.Vector3(2.4,0,0),radius:12}};
 function updateCamera(){camera.position.set(target.x+radius*Math.sin(azimuth)*Math.cos(elevation),target.y+radius*Math.sin(elevation),target.z+radius*Math.cos(azimuth)*Math.cos(elevation));camera.lookAt(target);camera.updateMatrixWorld();}
 // Lightweight software projection keeps exploration available without WebGL.
 function drawFlat(){const c=flat.getContext('2d');c.clearRect(0,0,width,height);c.fillStyle='#071321';c.fillRect(0,0,width,height);for(let i=0;i<130;i++){c.fillStyle='#7b97b277';c.fillRect((i*197%1000)/1000*width,(i*103%1000)/1000*height,1,1);}scene.updateMatrixWorld(true);const triangles=[];const project=v=>{v.project(camera);return [(v.x+1)*width/2,(1-v.y)*height/2,v.z];};scene.traverse(m=>{if(!m.isMesh||!m.visible||m.parent===engineering&&!engineering.visible||m.userData.jet)return;const pos=m.geometry.attributes.position,idx=m.geometry.index;const color=m.material.color.clone();for(let i=0;i<(idx?idx.count:pos.count);i+=3){const vs=[];for(let j=0;j<3;j++){const n=idx?idx.getX(i+j):i+j;vs.push(new THREE.Vector3().fromBufferAttribute(pos,n).applyMatrix4(m.matrixWorld));}const normal=new THREE.Vector3().subVectors(vs[1],vs[0]).cross(new THREE.Vector3().subVectors(vs[2],vs[0])).normalize();const shade=.55+.45*Math.abs(normal.dot(new THREE.Vector3(.3,.8,.5).normalize()));const points=vs.map(project);if(points.some(p=>p[2]<-1||p[2]>1))continue;triangles.push({points,z:points.reduce((s,p)=>s+p[2],0)/3,color:color.clone().multiplyScalar(shade).getHex()});}});const scale=flat.width/width,pixelWidth=flat.width,pixelHeight=flat.height,image=c.getImageData(0,0,pixelWidth,pixelHeight),pixels=image.data,depth=new Float32Array(pixelWidth*pixelHeight);depth.fill(Infinity);for(const tri of triangles){const [a,b,d]=tri.points.map(p=>[p[0]*scale,p[1]*scale,p[2]]),area=(b[1]-d[1])*(a[0]-d[0])+(d[0]-b[0])*(a[1]-d[1]);if(Math.abs(area)<.01)continue;const minX=Math.max(0,Math.floor(Math.min(a[0],b[0],d[0]))),maxX=Math.min(pixelWidth-1,Math.ceil(Math.max(a[0],b[0],d[0]))),minY=Math.max(0,Math.floor(Math.min(a[1],b[1],d[1]))),maxY=Math.min(pixelHeight-1,Math.ceil(Math.max(a[1],b[1],d[1])));for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const u=((b[1]-d[1])*(x+.5-d[0])+(d[0]-b[0])*(y+.5-d[1]))/area,v=((d[1]-a[1])*(x+.5-d[0])+(a[0]-d[0])*(y+.5-d[1]))/area;if(u<0||v<0||u+v>1)continue;const z=u*a[2]+v*b[2]+(1-u-v)*d[2],index=y*pixelWidth+x;if(z>=depth[index])continue;depth[index]=z;const offset=index*4;pixels[offset]=(tri.color>>16)&255;pixels[offset+1]=(tri.color>>8)&255;pixels[offset+2]=tri.color&255;pixels[offset+3]=255;}}c.putImageData(image,0,0);if(engineering.visible){c.strokeStyle='#80efc9';c.lineWidth=2;for(const line of paths){const [a,b]=line.map(v=>project(v.clone()));c.beginPath();c.moveTo(a[0],a[1]);c.lineTo(b[0],b[1]);c.stroke();}}
 }
 function resize(){width=host.clientWidth;height=host.clientHeight;camera.aspect=width/height;camera.clearViewOffset();if(width>700)camera.setViewOffset(width,height,-width*.09,0,width,height);camera.updateProjectionMatrix();if(renderer)renderer.setSize(width,height);else{const d=Math.min(devicePixelRatio,1.3);flat.width=width*d;flat.height=height*d;flat.getContext('2d').setTransform(d,0,0,d,0,0);}lastSignature='';}
 const observer=new ResizeObserver(resize);observer.observe(host);resize();
 return {fallback:!!flat,pick(x,y){updateCamera();scene.updateMatrixWorld(true);const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(x,y),camera);for(const hit of ray.intersectObject(model,true)){let object=hit.object;while(object&&object!==model){if(object.userData.component)return object.userData.component;object=object.parent;}}return null;},rotate(dx,dy){azimuth-=dx; elevation=clamp(elevation+dy,-1.15,1.15);},zoom(ratio){radius=clamp(radius*ratio,4,65);},reset(){azimuth=.62;elevation=.35;radius=34;target.set(0,0,0);selected=null;},focus(name){const f=focusPoints[name];if(!f)return;selected=name;target.copy(f.target);radius=f.radius;azimuth=name==='thrusters'?-1.05:.62;elevation=.35;},setEngineering(on){engineering.visible=on;groups.thrusters.traverse(m=>{if(m.userData.jet)m.visible=on;});lastSignature='';},get zoomPercent(){return Math.round(34/radius*100);},get radius(){return radius;},get orientation(){return {azimuth,elevation};},render(time,reduced){updateCamera();for(let i=0;i<dots.length;i++){const line=paths[i%paths.length],t=reduced?.5:(time*.3+i/12)%1;dots[i].position.lerpVectors(line[0],line[1],t);}const signature=[azimuth,elevation,radius,target.x,target.z,engineering.visible,engineering.visible&&!reduced?Math.floor(time*(flat?8:30)):0,width,height].join('|');if(signature===lastSignature)return;lastSignature=signature;if(renderer)renderer.render(scene,camera);else drawFlat();},dispose(){observer.disconnect();renderer?.dispose();scene.traverse(m=>{m.geometry?.dispose();if(m.material)m.material.dispose();});}}
}
